FROM golang:1.22 as builder
ARG GOPROXY=direct
WORKDIR /go/src/ehang.io/nps
COPY . .
RUN go get -d -v ./... 
RUN CGO_ENABLED=0 go build -ldflags="-w -s -extldflags -static" ./cmd/npc/npc.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /
COPY --from=builder /go/src/ehang.io/nps/npc .
COPY --from=builder /go/src/ehang.io/nps/conf/npc.conf /conf/npc.conf
VOLUME /conf
EXPOSE 80
ENTRYPOINT ["./npc"]
CMD ["-config=/conf/npc.conf"]